Fixed WarFogActivateTiles
dimi34alex/bug-strategy pull request #16
Opened 2024-10-21 13:25 UTC by denfranke

туман исчезает только от зданий и юнитов игрока

2024-10-22 14:20 UTC, workavast requested changes
Почему ты просто не унаследовал от VisibleWarFogZone два новых скрипта, один для юнитов, а другой для зданий, вместо того чтобы городить провероки на null? (если нет причин, то исправить)

2024-10-22 14:20 UTC, workavast commented on Assets/Source/Scripts/Tiles/VisibleWarFogZone.cs
> +        public ConstructionBase ScriptWithConstractionBase;//������ ������ ������ ����� �������� ��������������, ����� ���� ����� null
- есть атрибут [SerializeField], чтобы через инспектор можно было указывать значения protected и private полей
- есть атрибут [Tooltip("описание")], при наведении курсора на поле в инспекторе будет показано описание. Туда можно было бы сунуть инфу о том что поле может быть null
- другие атрибуты можно глянуть здесь: https://github.com/teebarjunk/Unity-Built-In-Attributes

2024-10-22 14:20 UTC, workavast commented on Assets/Source/Scripts/Tiles/VisibleWarFogZone.cs
> +                if(ScriptWithUnitBase.Affiliation == AffiliationEnum.Team1)
у игрока не обязательно должен быть Team1, он может быть и другим. В MissionData есть поле PlayerAffiliation, надо сравнивать с ним. Его надо инжектить через атрибут [Inject], это атрибут Zenject

[Inject] private readonly MissionData _missionData;

2024-10-25 12:26 UTC, workavast requested changes

2024-10-25 12:26 UTC, workavast commented on Assets/Source/Scripts/Tiles/VisibleWarFogZone.cs
> +            GetAffiliationAdd(component);
ты мог просто этот же метод за-override-ить в UnitVisibleWarFogZone и здания, не создавая новые виртуальные методы

2024-10-25 12:26 UTC, workavast commented on Assets/Source/Scripts/Tiles/WarFog/ConstractionVisibleWarFogZone.cs
> +        public ConstructionBase ScriptWithConstructionBase;
почему public, а не [SerializeField] private?

2024-10-25 12:26 UTC, workavast commented on Assets/Source/Scripts/Tiles/WarFog/UnitVisibleWarFogZone.cs
> +        public UnitBase ScriptWithUnitBase;
почему public, а не [SerializeField] private?

2024-10-25 12:40 UTC, denfranke commented on Assets/Source/Scripts/Tiles/WarFog/ConstractionVisibleWarFogZone.cs
> +        public ConstructionBase ScriptWithConstructionBase;
ща сделаю

2024-10-25 12:41 UTC, denfranke commented on Assets/Source/Scripts/Tiles/VisibleWarFogZone.cs
> +                if(ScriptWithUnitBase.Affiliation == AffiliationEnum.Team1)
спасибо

2024-10-25 17:45 UTC, workavast approved these changes

2024-10-25 17:45 UTC, merged