Camera movement
dimi34alex/bug-strategy pull request #23
Opened 2024-11-11 09:06 UTC by denfranke

2024-11-12 13:30 UTC, workavast requested changes
- убрать таймер
- раз одновременно может быть либо движение колесиком либо курсором, то разделить их на отдельные методы, вместо того чтобы мешать все в кашу. Так чтобы одновременно мог выполняться только один из них. Если используется колесико то обработка движения через колесико, не трогая метод расчета через курсор; если колесико не используется то просчитывать движение через положение курсора, не трогая метод просчета колесика
- расчет идет через колв-о пикселей от карая экрана, это значит при разных разрешениях, будет разный процент от экрана (20 в 1080p это ~2%, а в 720 это ~2.7%, а 4к ~1%), не критично но всё таки. можно просто в зависимости от текущего разрешения просто скейлить порог

2024-11-14 16:56 UTC, workavast requested changes
- теперь камера всегда движется, а не только когда курсор у края экрана
- зачем разделил на два скрипта, которые работаю независимо друг от друга (см. следующий пункт)?
- почему выключил скрипт управления через скрол на сцене? Игрок может и колесиком и курсором передвинуть камеру. Это должно быть доступно одновременно, но в один момент работать только один способ. Если используется колесико то не просчитывать курсор, если колесико не используется просчитывать через курсор. Там же уже было два ифа с колесиком, можно было сделать типа if(колесико используется) MoveByScroll else MoveByCursor и всё.

2024-11-14 16:56 UTC, workavast commented on Assets/Source/Scripts/CameraMovement/CameraMoverCursor.cs
> +            SizeBorderToMove = Mathf.Min(Screen.width, Screen.height) / PercentageOfScreen;
игрок может менять разрешение просто рассчитывай каждый раз при вычислении позиции курсора, все равно это никак не повлияет на производительность, но не надо будет выдумывать велосипед с тем как обновлять этот параметр если игрок поменяет разрешение в настройках во время игры

2024-11-18 21:17 UTC, denfranke commented on Assets/Source/Scripts/CameraMovement/CameraMoverCursor.cs
> +            SizeBorderToMove = Mathf.Min(Screen.width, Screen.height) / PercentageOfScreen;
готого

2024-11-22 14:20 UTC, workavast approved these changes

2024-11-22 14:37 UTC, merged