Добавил спрайты и изменил префабы какие смог
dimi34alex/bug-strategy pull request #25
Opened 2024-11-24 11:42 UTC by denfranke

2024-11-24 16:32 UTC, workavast requested changes
- в префабах надо было изменить только спрайт у объекта Skin, не надо было добавлять другие спрайты
- почему не изменены конфиги, в которых надо было указать все спрайты для всех уровней?
- создай спрайт атласы, для каждой фракции свой
- пофиксь размеры, а то некоторые спрайты теперь слишком маленькие, а какие-то слишком большие

2024-11-26 14:34 UTC, workavast requested changes
- почему изменены скрипты и некоторые другие вещи, которые не должны быть изменены? Pool.cs, FactorySingle.cs, UnitsTargetPositionMarkerConfig и другие. Откатить все эти изменения
- в чем был смысл удалять спрайты из объектов внутреи префабов, вместо того чтобы удалить эти не нужные объекты? Удалить эти не нужные объекты
![image](https://github.com/user-attachments/assets/2cdf1e10-754f-4253-aa0c-c65d31357ce6)
- у атласов не верное ограничение размера 2048
- в атласах дубликаты спрайтов других размеров (например две вышки разных размеров и другие)
- раз есть новые варианты старых спрайтов другого размера (например вышка 1024 и 750), установить новые спрайты, а старые удалить из проекта
- в конфигах зданий всё еще не установлены спрайты
- не сброшены изменения цвета, о чем было написано в Week
![image](https://github.com/user-attachments/assets/acd27049-ed9d-4b6e-81ca-9aaacdbad958)

2024-11-28 16:18 UTC, workavast requested changes
> * почему изменены скрипты и некоторые другие вещи, которые не должны быть изменены? Pool.cs, FactorySingle.cs, UnitsTargetPositionMarkerConfig и другие, я не знаю че ты сделал но так явно быть не должно, потому что более новые изменения, которые я писал заменены на более старые. Откатить все эти изменения

проблема не решена

2024-11-28 19:50 UTC, denfranke commented
Брехня, я ничего там не менял может ты не актуальное проверял?

2024-11-29 06:28 UTC, workavast commented
сам зайди в раздел Files changed
![image](https://github.com/user-attachments/assets/d5ab79c0-96c6-4209-a5bb-35b39747c3ac)

2024-11-29 06:32 UTC, workavast commented
а в разделе Commits можно посмотреть изменения в отдельных комитах и найти тот(или те) в котором это произошло

2024-11-29 08:10 UTC, closed without merging