RightBottomUIBlock
dimi34alex/bug-strategy pull request #26
Opened 2024-11-25 16:35 UTC by Makar-Tsvetukhin

Сделал выделение скрипт выделение юнитов более правильным(Убрал удаление и создание иконок, теперь там есть изначальный пул, который по необходимости активируется, убрал сетку, которая была в самом скрипте, на "block" поставил сетку которая ставит правильно иконки).
Пока так и не понял как надо сделать с центральным нижнем интерфейсом, так что пока что при выборе здания в правой части будут отображаться все юниты внутри, при клике на иконку, юниты будут выводиться из здания

Скрипты в  bug-strategy\Assets\Source\Scripts\UI\Elements\Block
префаб один называется IconBlock  в bug-strategy\Assets\Source\Prefabs\UI\BarView

пул связанные с Веткой(Fix unit exit), и мерж от основной ветки в мою(мерж в fixUnit) можно удалить. В целом и саму ветку (Fix unit exit) тоже можно удалить, она устарела и там ничего полезного больше нет.

2024-11-26 13:55 UTC, workavast requested changes
- кривое отображение 
![image](https://github.com/user-attachments/assets/0e789b67-aa94-4943-8d9d-ed57b3087c0d)
- если при выделенной пчеле кликнуть на здание, в котором есть юнит, то иконки багуют
![image](https://github.com/user-attachments/assets/a82e63e0-fd52-4265-b4c0-7c55e0aecb00)
- в здании может быть больше одного юнита, у тебя отображается только один. В конфигах зданий, в настройках уровня есть пункт с количеством юнитов (вроде бы hider capacity), можешь его увеличить для тестов,

2024-11-26 13:55 UTC, workavast commented on Assets/Source/Scripts/UI/Elements/Block/UnitSelectionUI.cs
> +            IReadOnlyList<UnitBase> selectedUnits = _unitsSelector.GetSelectedUnits();
допиши событие в unit selector условно OnChanged и обновляй иконки при срабатывании события, а не в update

2024-11-26 13:55 UTC, workavast commented on Assets/Source/Scripts/UI/Elements/Block/BuildingUnitsUI.cs
> +        UnitBase extractedUnit = currentHiderConstruction.Hider.ExtractUnit(0, extractPosition);
у метода ExtractUnit есть перегрузка без позиции, можно было и не вычислять позицию самому, а просто передать индекс для извлечения. Но окей, исправлять не обязательно

2024-11-26 19:12 UTC, Makar-Tsvetukhin commented
Всё исправил, отображение должно быть нормальным теперь.
Починил баг, но теперь когда кликаешь на здание ПКМ, то снимается всё выделение со всех юнитов, по другому не придумал как сделать, раньше было так: если юниты уже выделены и ты кликаешь на задние, то выделение получается и на юнитах и на здание оставалось.

Со спрятанными юнитами сделал нормально, ограничение пока что в 10 юнитов поставил в UI(именно в самом интерфейсе block отображается до 10 иконок), если надо будет больше, можно будет и больше поставить.


Сделал событие OnSelectionChanged и упразднил update

2024-11-27 18:31 UTC, Makar-Tsvetukhin commented
Код почистил, по идеи можно мерж делать

2024-11-28 15:53 UTC, workavast commented
> Всё исправил, отображение должно быть нормальным теперь. Починил баг, но теперь когда кликаешь на здание ПКМ, то снимается всё выделение со всех юнитов, по другому не придумал как сделать, раньше было так: если юниты уже выделены и ты кликаешь на задние, то выделение получается и на юнитах и на здание было, теперь вроде пологичнее, если выделяешь здание выделяется только здание, если юнита, то выделяется только юнит

я вчера смотрел только код и не заметил этого, но юниты должны быть выделены одновременно со зданием, потому смена профессии у муравья так работает: выделяешь муравья -> выделяешь здание -> кликаешь на инструмент/оружие -> выделенный юнит получает приказ на взятие этого инструмента из этого здания

2024-11-28 15:53 UTC, workavast requested changes
написал выше

2024-11-30 15:12 UTC, workavast approved these changes
я внес доработки, можешь посмотреть если хочешь

2024-11-30 15:14 UTC, merged